-- 코드를 입력하세요
SELECT HISTORY_ID, 
    floor(C.daily_fee * (DATEDIFF(END_DATE, START_DATE) + 1 ) * (1 - IFNULL(P.discount_rate , 0) / 100))
    as FEE
FROM  CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
-- 할인율이 어떤게 적용되는지 붙히기 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE 
AND P.DURATION_TYPE = (
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) >= 7  THEN '7일 이상'
        END
    )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID desc
;