-- 코드를 입력하세요
SELECT DISTINCT C.car_id as car_id
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.car_id = H.car_id
WHERE MONTH(H.START_DATE) = '10' 
AND C.CAR_TYPE = '세단'
ORDER BY CAR_ID desc

;